### ISSUE TITLE
Add a license to the repository!

### ISSUE THREAD

**Issue by Mollnitz** [benhuds/Agda#1]
Hello! 
I represent a group of students from Denmark.
For our master thesis we are very interested in looking into and elaborating on some of your work, however that is going to be legally complicated due to the fact that this repository as it is right now doesn't have a license attached to it.

Would you consider adding a license?
Thanks!

**Comment by benhuds** [comment]
Hi @Mollnitz, I'm sorry I'm just getting to this! I added a license to the repository just now. Does the license allow you to continue looking into/elaborating on the work in the repository as requested?
